source 'https://cdn.cocoapods.org/'
use_frameworks!

platform :ios, '11.0'

target 'VinBaseComponents_Example' do
  pod 'VinBaseComponents', :path => '../'

  target 'VinBaseComponents_Tests' do
    inherit! :search_paths

    
  end
end
